# Generated by Django 6.1.1 on 2026-10-06 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab_tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_phone', models.CharField(max_length=20)),
                ('patient_age', models.IntegerField(default=30)),
                ('patient_gender', models.CharField(default='Male', max_length=10)),
                ('collection_type', models.CharField(choices=[('HOME_COLLECTION', 'Free Home Sample Collection'), ('CENTER_VISIT', 'Diagnostic Center / Shop Visit')], default='HOME_COLLECTION', max_length=20)),
                ('collection_address', models.TextField(blank=True)),
                ('landmark', models.CharField(blank=True, max_length=150)),
                ('pincode', models.CharField(default='831019', max_length=10)),
                ('preferred_date', models.DateField()),
                ('preferred_time_slot', models.CharField(default='07:00 AM - 09:00 AM', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('TESTING', 'Testing / In Lab'), ('REPORT_READY', 'Report Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('phlebotomist_notes', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_collections', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.booking')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab_tests.labtest')),
            ],
        ),
    ]
