# Generated by Django 6.1.1 on 2026-10-06 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('doctor_name', models.CharField(default='Dr. R. K. Mukherjee (MD, Pathologist)', max_length=150)),
                ('verification_code', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published & Verified')], default='PUBLISHED', max_length=20)),
                ('overall_summary', models.TextField(blank=True, default='All parameters analyzed using automated chemiluminescence and calibrated analyzers.')),
                ('parameters_data', models.JSONField(blank=True, default=list)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('sample_collected_at', models.DateTimeField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='bookings.booking')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
