export const FALLBACK_CATEGORIES = [
  { id: 1, name: 'Routine Blood Tests', slug: 'routine', description: 'Essential daily blood counts and baseline diagnostics', icon: 'Droplet', tests_count: 5 },
  { id: 2, name: 'Organ & Profile Panels', slug: 'profiles', description: 'Complete organ function panels (Liver, Kidney, Lipid, Thyroid)', icon: 'Activity', tests_count: 4 },
  { id: 3, name: 'Diabetes & Sugar Tests', slug: 'diabetes', description: 'Blood glucose monitoring and HbA1c screening', icon: 'Target', tests_count: 3 },
  { id: 4, name: 'Vitamins & Hormones', slug: 'vitamins', description: 'Critical vitamin levels, bone health and hormonal balances', icon: 'Sun', tests_count: 2 },
  { id: 5, name: 'Infection & Fever Panels', slug: 'fever', description: 'Dengue, Typhoid, Malaria, and viral markers', icon: 'ShieldAlert', tests_count: 2 },
  { id: 6, name: 'Full Body Health Packages', slug: 'packages', description: 'Comprehensive preventive health checkups at discounted bundle rates', icon: 'Package', tests_count: 3 },
];

export const FALLBACK_TESTS = [
  {
    id: 1,
    name: 'Complete Blood Count (CBC) with ESR',
    code: 'ACC-CBC',
    category: 1,
    category_name: 'Routine Blood Tests',
    category_slug: 'routine',
    price: 350.00,
    discount_price: 299.00,
    final_price: 299.00,
    sample_type: 'EDTA Whole Blood',
    fasting_required: false,
    turnaround_hours: 6,
    parameters_included: 'Hemoglobin, TLC, DLC, Platelet Count, RBC, PCV, MCV, MCH, MCHC, ESR',
    preparation_instructions: 'No special fasting required. Can be done anytime.',
    description: 'Measures cell counts in blood to evaluate overall health and detect disorders like anemia and infection.',
    is_popular: true,
    is_active: true
  },
  {
    id: 2,
    name: 'Lipid Profile (Cholesterol Panel)',
    code: 'ACC-LIPID',
    category: 2,
    category_name: 'Organ & Profile Panels',
    category_slug: 'profiles',
    price: 750.00,
    discount_price: 599.00,
    final_price: 599.00,
    sample_type: 'Serum',
    fasting_required: true,
    fasting_hours: 10,
    turnaround_hours: 12,
    parameters_included: 'Total Cholesterol, HDL Cholesterol, LDL Cholesterol, VLDL, Triglycerides, Cholesterol/HDL Ratio',
    preparation_instructions: 'Requires 10-12 hours of overnight fasting. Water is permitted.',
    description: 'Assesses cardiovascular risk and lipid metabolism for heart health.',
    is_popular: true,
    is_active: true
  },
  {
    id: 3,
    name: 'Thyroid Profile Total (T3, T4, TSH)',
    code: 'ACC-THYROID',
    category: 2,
    category_name: 'Organ & Profile Panels',
    category_slug: 'profiles',
    price: 650.00,
    discount_price: 499.00,
    final_price: 499.00,
    sample_type: 'Serum',
    fasting_required: true,
    fasting_hours: 8,
    turnaround_hours: 12,
    parameters_included: 'Triiodothyronine (T3), Thyroxine (T4), Thyroid Stimulating Hormone (TSH)',
    preparation_instructions: 'Fasting preferred. Morning sample recommended before thyroid medication.',
    description: 'Evaluates thyroid gland function to detect hyperthyroidism or hypothyroidism.',
    is_popular: true,
    is_active: true
  },
  {
    id: 4,
    name: 'Liver Function Test (LFT)',
    code: 'ACC-LFT',
    category: 2,
    category_name: 'Organ & Profile Panels',
    category_slug: 'profiles',
    price: 800.00,
    discount_price: 649.00,
    final_price: 649.00,
    sample_type: 'Serum',
    fasting_required: true,
    fasting_hours: 8,
    turnaround_hours: 12,
    parameters_included: 'Bilirubin (Total, Direct, Indirect), SGOT/AST, SGPT/ALT, Alkaline Phosphatase, Total Protein, Albumin, Globulin, A/G Ratio',
    preparation_instructions: 'Overnight fasting of 8-10 hours recommended.',
    description: 'Screens for liver injury, jaundice, hepatitis, and protein synthesis health.',
    is_popular: true,
    is_active: true
  },
  {
    id: 5,
    name: 'Kidney Function Test (KFT) / Renal Profile',
    code: 'ACC-KFT',
    category: 2,
    category_name: 'Organ & Profile Panels',
    category_slug: 'profiles',
    price: 800.00,
    discount_price: 649.00,
    final_price: 649.00,
    sample_type: 'Serum',
    fasting_required: false,
    turnaround_hours: 12,
    parameters_included: 'Blood Urea, Serum Creatinine, Uric Acid, BUN, Calcium, Phosphorus, Electrolytes (Na, K, Cl)',
    preparation_instructions: 'Stay adequately hydrated before test.',
    description: 'Checks kidney filtering capacity and fluid/electrolyte balance.',
    is_popular: true,
    is_active: true
  },
  {
    id: 6,
    name: 'HbA1c (Glycated Hemoglobin)',
    code: 'ACC-HBA1C',
    category: 3,
    category_name: 'Diabetes & Sugar Tests',
    category_slug: 'diabetes',
    price: 550.00,
    discount_price: 450.00,
    final_price: 450.00,
    sample_type: 'EDTA Whole Blood',
    fasting_required: false,
    turnaround_hours: 8,
    parameters_included: 'HbA1c %, Estimated Average Glucose (eAG)',
    preparation_instructions: 'No fasting required. Measures 3-month average blood sugar.',
    description: 'Gold standard test for diabetes monitoring and long-term glycemic control.',
    is_popular: true,
    is_active: true
  },
  {
    id: 7,
    name: 'Fasting Blood Sugar (FBS)',
    code: 'ACC-FBS',
    category: 3,
    category_name: 'Diabetes & Sugar Tests',
    category_slug: 'diabetes',
    price: 120.00,
    discount_price: 99.00,
    final_price: 99.00,
    sample_type: 'Fluoride Plasma',
    fasting_required: true,
    fasting_hours: 8,
    turnaround_hours: 4,
    parameters_included: 'Fasting Plasma Glucose',
    preparation_instructions: 'Strict 8 to 10 hours overnight fasting required.',
    description: 'Evaluates baseline glucose level after fasting.',
    is_popular: false,
    is_active: true
  },
  {
    id: 8,
    name: 'Post Prandial Blood Sugar (PPBS)',
    code: 'ACC-PPBS',
    category: 3,
    category_name: 'Diabetes & Sugar Tests',
    category_slug: 'diabetes',
    price: 120.00,
    discount_price: 99.00,
    final_price: 99.00,
    sample_type: 'Fluoride Plasma',
    fasting_required: false,
    turnaround_hours: 4,
    parameters_included: 'Post-Meal Glucose',
    preparation_instructions: 'Sample given exactly 2 hours after commencing a meal.',
    description: 'Evaluates how body manages glucose load after a meal.',
    is_popular: false,
    is_active: true
  },
  {
    id: 9,
    name: 'Vitamin D (25-Hydroxy)',
    code: 'ACC-VITD',
    category: 4,
    category_name: 'Vitamins & Hormones',
    category_slug: 'vitamins',
    price: 1200.00,
    discount_price: 899.00,
    final_price: 899.00,
    sample_type: 'Serum',
    fasting_required: false,
    turnaround_hours: 24,
    parameters_included: '25-OH Vitamin D3 / D2',
    preparation_instructions: 'No fasting required.',
    description: 'Crucial for bone density, calcium absorption, and immune function.',
    is_popular: true,
    is_active: true
  },
  {
    id: 10,
    name: 'Vitamin B12 (Cyanocobalamin)',
    code: 'ACC-VITB12',
    category: 4,
    category_name: 'Vitamins & Hormones',
    category_slug: 'vitamins',
    price: 1100.00,
    discount_price: 850.00,
    final_price: 850.00,
    sample_type: 'Serum',
    fasting_required: true,
    fasting_hours: 8,
    turnaround_hours: 24,
    parameters_included: 'Serum Vitamin B12',
    preparation_instructions: 'Fasting of 8 hours recommended.',
    description: 'Essential for nerve function, neurological health, and red cell production.',
    is_popular: false,
    is_active: true
  },
  {
    id: 11,
    name: 'Dengue NS1 Antigen & IgM/IgG Serology',
    code: 'ACC-DENGUE',
    category: 5,
    category_name: 'Infection & Fever Panels',
    category_slug: 'fever',
    price: 950.00,
    discount_price: 750.00,
    final_price: 750.00,
    sample_type: 'Serum',
    fasting_required: false,
    turnaround_hours: 6,
    parameters_included: 'Dengue NS1 Antigen, Dengue IgM Antibody, Dengue IgG Antibody',
    preparation_instructions: 'Can be done at any time during fever illness.',
    description: 'Rapid detection of dengue viral infection during early acute and convalescent phases.',
    is_popular: false,
    is_active: true
  },
  {
    id: 12,
    name: 'Complete Urine Examination (CUE Routine & Microscopic)',
    code: 'ACC-URINE',
    category: 1,
    category_name: 'Routine Blood Tests',
    category_slug: 'routine',
    price: 220.00,
    discount_price: 180.00,
    final_price: 180.00,
    sample_type: 'Clean Catch Midstream Urine',
    fasting_required: false,
    turnaround_hours: 6,
    parameters_included: 'Color, pH, Specific Gravity, Protein/Albumin, Sugar, Ketones, Pus Cells, RBCs, Epithelial Cells, Crystals, Casts',
    preparation_instructions: 'Clean container provided. First morning mid-stream urine preferred.',
    description: 'Detects urinary tract infections, kidney disorders, and metabolic indicators.',
    is_popular: false,
    is_active: true
  },
  {
    id: 13,
    name: 'Accusure Basic Health Checkup Package',
    code: 'ACC-PKG-BASIC',
    category: 6,
    category_name: 'Full Body Health Packages',
    category_slug: 'packages',
    price: 1900.00,
    discount_price: 1199.00,
    final_price: 1199.00,
    sample_type: 'Blood & Urine',
    fasting_required: true,
    fasting_hours: 10,
    turnaround_hours: 12,
    parameters_included: 'CBC (24 Parameters), Fasting Blood Sugar, Lipid Profile, Kidney Function Test, Urine Routine',
    preparation_instructions: '10-12 hours overnight fasting. Includes free home sample collection.',
    description: 'A foundational preventive health screening covering vital organs and metabolism.',
    is_popular: true,
    is_active: true
  },
  {
    id: 14,
    name: 'Accusure Master Full Body Health Package (70+ Tests)',
    code: 'ACC-PKG-MASTER',
    category: 6,
    category_name: 'Full Body Health Packages',
    category_slug: 'packages',
    price: 3500.00,
    discount_price: 1999.00,
    final_price: 1999.00,
    sample_type: 'Blood & Urine',
    fasting_required: true,
    fasting_hours: 10,
    turnaround_hours: 24,
    parameters_included: 'CBC, Liver Function Test (LFT), Kidney Function Test (KFT), Lipid Profile, Thyroid Profile (T3/T4/TSH), HbA1c, Fasting Sugar, Urine Analysis',
    preparation_instructions: '10-12 hours overnight fasting. Comprehensive health review by MD Pathologist.',
    description: 'Our most popular comprehensive diagnostic health screening for complete wellness.',
    is_popular: true,
    is_active: true
  },
  {
    id: 15,
    name: 'Accusure Senior Citizen Care Comprehensive (85+ Tests)',
    code: 'ACC-PKG-SENIOR',
    category: 6,
    category_name: 'Full Body Health Packages',
    category_slug: 'packages',
    price: 5200.00,
    discount_price: 2999.00,
    final_price: 2999.00,
    sample_type: 'Blood & Urine',
    fasting_required: true,
    fasting_hours: 10,
    turnaround_hours: 24,
    parameters_included: 'Master Package + Vitamin D3 + Vitamin B12 + Calcium + Iron Studies + Cardiac Risk Markers',
    preparation_instructions: '10-12 hours overnight fasting. Phlebotomist visits home with comfortable gentle draw needles.',
    description: 'Advanced preventive screening specially curated for seniors aged 50+.',
    is_popular: true,
    is_active: true
  }
];

export const FALLBACK_DEMO_USERS = {
  admin: {
    id: 1,
    username: 'admin',
    email: 'ashwanarya20042004@gmail.com',
    first_name: 'Ashwani',
    last_name: 'Arya',
    role: 'admin',
    phone_number: '7205573352',
    address: 'Shop No. 7, MIJO HOUSE, Sunday Market, Birsanagar, Jamshedpur',
    city: 'Jamshedpur',
    gender: 'Male'
  },
  patient_priya: {
    id: 4,
    username: 'patient_priya',
    email: 'priya.sharma@example.com',
    first_name: 'Priya',
    last_name: 'Sharma',
    role: 'patient',
    phone_number: '9123456780',
    address: 'Flat 302, Green Valley Apartments, Birsanagar, Jamshedpur',
    city: 'Jamshedpur',
    gender: 'Female'
  },
  dr_mukherjee: {
    id: 2,
    username: 'dr_mukherjee',
    email: 'dr.mukherjee@accusure.com',
    first_name: 'R. K.',
    last_name: 'Mukherjee',
    role: 'doctor',
    phone_number: '9876543210',
    address: 'Telco Colony, Jamshedpur',
    city: 'Jamshedpur',
    gender: 'Male'
  },
  staff_rahul: {
    id: 3,
    username: 'staff_rahul',
    email: 'rahul.verma@accusure.com',
    first_name: 'Rahul',
    last_name: 'Verma',
    role: 'staff',
    phone_number: '7205573399',
    address: 'Birsanagar Zone 3, Jamshedpur',
    city: 'Jamshedpur',
    gender: 'Male'
  }
};

