# Generated by Django 6.1.1 on 2026-10-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('TUBES', 'Collection Tubes (EDTA, Serum, Fluoride)'), ('SYRINGES', 'Syringes & Needles'), ('PPE', 'Gloves, Masks & PPE'), ('CONTAINERS', 'Sample Collection Containers'), ('REAGENTS', 'Diagnostic Reagents & Strips'), ('MISC', 'Other Consumables')], default='TUBES', max_length=30)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(default='Pieces', help_text='e.g., Pieces, Boxes, Vials, Packs', max_length=50)),
                ('reorder_level', models.IntegerField(default=20, help_text='Threshold to trigger low-stock warning')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('supplier', models.CharField(blank=True, default='MedSupply Healthcare Jamshedpur', max_length=150)),
                ('last_restocked', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
