# Generated by Django 6.1.1 on 2026-10-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
